- name: install kubectl
  apt:
    name: kubectl=1.26.0-00
    state: present
    force: yes 

# Initialize and set up the cluster and master node 
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: kuser
  file:
    path: $HOME/.kube
    state: directory
    mode: u=rwx,g=rx,o=rx #0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kuser/.kube/config
    remote_src: yes
    owner: kuser

- name: Pause for 1 minute to build app cache
  ansible.builtin.pause:
    minutes: 1

- name: install Pod network
  become: true
  become_user: kuser
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml >> pod_network_setup.txt  # https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: restart kubelet
  service: name=kubelet state=restarted

- name: untaint nodes 
  shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

# Create and save join token
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw 

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Store join command
  action: copy content="{{ join_command }}" dest="/etc/kubernetes/join.command"
